# ->->->->-> Primary <-<-<-<-<-
exp_name: "temp"
result_dir: "./trained_models"
num_classes: 2
init_type: "kaiming_normal"


# ->->->->-> Model <-<-<-<-<-
arch: "dan"
embed_dim: 300
hidden_dim: 256
dropout: 0.2


# ->->->->-> Train <-<-<-<-<-
epochs: 100
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9

#warmup
warmup_epochs: 0
warmup_lr: 0.1


# ->->->->-> Dataset <-<-<-<-<-
dataset: CIFAR10
batch_size: 128
test_batch_size: 128
data_dir: "./dataset"
data_fraction: 1.0


# ->->->->-> Misc <-<-<-<-<-
gpu: "0"
seed: 1234
print_freq: 100